#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

use_frameworks!

target 'NetHelper_Example' do
  pod 'NetHelper', :path => '../'

  target 'NetHelper_Tests' do
    inherit! :search_paths

    pod 'Alamofire', '~> 5.0.5'

  end
end
